name: "Build"

env:
  RUST_VERSION: "1.60.0"
  RUST_BACKTRACE: full

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checks:
    name: Run checks
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: clippy, rustfmt

      - name: Cache cargo resources
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: deps
          cache-on-failure: true

      - name: Cargo fmt
        run: cargo fmt --all -- --check

      - name: Cargo check
        run: cargo check --workspace

      - name: Debug build
        run: cargo build --all-targets

      - name: Run tests
        run: cargo test --workspace

      - name: Run tests (no rayon)
        run: cargo test --no-default-features

      - name: Release build
        run: cargo build --release --all-targets
